### ISSUE TITLE
[Bug]: NameError: name 'groupport' is not defined

### ISSUE THREAD

**Issue by bywhite0** [watagashi-uni/twitterpush#2]
> 已对`start.py`进行修改(将文件路径的`\`替换成`/`)使Linux可正常读取文件

## 系统信息及软件版本

- Arch Linux arm64
- Python: 3.10.5
- go-cqhttp: 1.0.0-rc3

## 预期效果

正常推送

## 实际效果

即将推送时抛出错误

## 日志

```
2022-08-08 18:39:56 检查推特列表
2022-08-08 18:39:57 检测到列表变动
2022-08-08 18:39:57 确认更新
2022-08-08 18:40:00 即将推送UN_NERV
Job "checktwitter (trigger: interval[0:00:15], next run at: 2022-08-08 18:40:11 CST)" raised an exception
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "/root/twitterpush/start.py", line 66, in checktwitter
sendpush(authorid, twiid)
File "/root/twitterpush/start.py", line 77, in sendpush
sendgroupmsg(qunhao, rf'[CQ:image,file=file:///{os.getcwd()}/piccache/{twiid}.png]', groupport)
NameError: name 'groupport' is not defined
```

**Comment by watagashi-uni** [comment]
根目录有个`config.example.py`，得改成·`config.py`，cqhttp端口号也要填在这

**Comment by bywhite0** [comment]
已确认`config.py`配置如下：
```
proxy = ''
proxies = ''
# 不用代理改 None
rsshub = 'https://rsshub.app/'  # rsshub地址
twitterlist = '...'
googleapiskey = '...'
groupport = 5700  # cqhttp端口
guildport = 1988  # 频道bot http端
```

go-cqhttp相关配置如下：
```
servers:
  - http:
      address: 127.0.0.1:5700
      timeout: 5
      long-polling:
        enabled: false
        max-queue-size: 2000
```

仍可复现

**Comment by watagashi-uni** [comment]
抱歉，我的问题，从我bot工程把这个抽离的时候加了自定义端口然后忘了import了
把 `from config` 那句改成  `from config import rsshub, twitterlist, proxies, guildport, groupport` 就好了

**Comment by bywhite0** [comment]
感谢，问题已解决。
